config/routes.rb
Rails.application.routes.draw do
  post 'users/social_auth'
  get 'users/social_auth_vk'
  get '/privacy_policy', to: redirect('/privacy_policy.html')
  resources :push_notification_subscriptions
  resources :events
  resources :costumes do
    resources :comments
    resources :photos, only: [:destroy]
  end
  resources :cosplayers, only: [:show, :edit, :update] do
    member do
      post 'subscribe'
      post 'unsubscribe'
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "costumes#index"
end

app/models/costume.rb
class Costume < ApplicationRecord
  is_impressionable counter_cache: true
  paginates_per 25
  include PgSearch
  pg_search_scope :search_by_name,
                  against: :name,
                  using: {
                      tsearch: { any_word: true },
                      trigram: { threshold: 0.3 }
                  }
  validates_presence_of :name, :user
  validates_length_of :name, minimum: 3, maximum: 100
  validates_length_of :desc, minimum: 3, maximum: 455, allow_blank: true
  scope :with_eager_loaded_photos, -> { eager_load(photos_attachments: :blob) }
  belongs_to :user, counter_cache: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_many_attached :photos
  accepts_nested_attributes_for :photos_attachments, allow_destroy: true
  before_update :purge_blobs

  def send_comment_notification(text)
    user.push_notification_subscriptions.each do |sub|
      sub.send_push(text, "#{ENV['HOST']}/costumes/#{id}")
    end
  end

  private

  # destroying photos via nested attributes
  def purge_blobs
    photos_attachments.each do |photo_attachment|
      if photo_attachment.marked_for_destruction?
        photo_attachment.blob.purge_later
      end
    end
  end

end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :find_costume, only: [:show, :edit, :update, :destroy]
  after_action :photos_counter_cache, only: [:create, :edit, :update]
  impressionist actions: [:show], unique: [:user_id, :impressionable_type, :impressionable_id]

  def index
    name = params.dig(:search, :name)
    @costumes =
      Costume
      .with_eager_loaded_photos
      .where('photos_count > ?', 0)
      .try { |costumes|
        name ?
            costumes.search_by_name(name) :
            costumes }
      .order(created_at: :desc)
      .page(params[:page])
    desc = 'Cosplay from popular cosplayers in the Casply community, your best resource to discover and connect with cosplayers worldwide.'
    set_meta_tags description: desc,
                  og: {
                      type: 'website',
                      description: desc,
                  }
  end

  def new
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def create
    @costume = current_user.costumes.new(costume_params)
    if @costume.save
      render json: @costume
    else
      render json: { errors: @costume.errors.full_messages }, status: 400
    end
  end

  def edit
    unless user_costume?
      render json: { errors: ['Unauthorized access'] }, status: 401
    end
    gon.push({
      costume_id: @costume.id,
      name: @costume.name,
      desc: @costume.desc,
      photos: @costume.photos.map do |photo|
        {
          id: photo.id,
          preview: rails_representation_url(photo.variant(resize: '100', interlace: 'plane'))
        }
      end
    })
  end

  def show
    @comments =
      @costume
        .comments
        .includes(:user)
        .order(created_at: :desc)
        .page(params[:page])

    @js_variables = {
        canRemove: user_signed_in? && @costume.user_id == current_user.id,
        costumeId: @costume.id,
        photos: @costume.photos.order(created_at: :desc).map do |photo|
          metadata = if photo.metadata[:height]
                       photo.metadata
                     else
                       photo.analyze
                       photo.metadata
                     end
          {
              id: photo.id,
              src: rails_representation_url(
                photo
                  .variant(resize: '1024', interlace: 'plane')),
              lq_src: rails_representation_url(
                  photo
                      .variant(resize: '350', interlace: 'plane')),
              w: metadata['width'] || 1024,
              h: metadata['height'] || 1024,
              title: ''
          }
        end
    }
    gon.push(@js_variables)

    desc = @costume.desc.truncate(160)
    set_meta_tags description: desc,
        og: {
            title: "Cosplay - #{@costume.name}",
            type: 'website',
            description: desc,
            image: @js_variables.dig(:photos, 0, :url)
        }
  end

  def update
    unless user_costume?
      render json: { errors: ['Unauthorized access'] }, status: 401
    end
    if @costume.update(costume_params)
      render json: {}, status: 201
    else
      render json: { messages: @costume.errors.full_messages }, status: 401
    end
  end

  def destroy
    return redirect_to root_path unless user_costume?
    @costume.destroy
    respond_to do |format|
      format.html { redirect_to cosplayer_path(current_user), notice: t('costumes.was_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def find_costume
    @costume = Costume.with_eager_loaded_photos.find(params[:id])
  end

  def costume_params
    params.require(:costume).permit(
      :name,
      :desc,
      photos: [],
      photos_attachments_attributes: [:id, :_destroy],
    )
  end

  def photos_counter_cache
    @costume.update(photos_count: @costume.photos.count)
  end

  def user_costume?
    @costume.user_id == current_user.id
  end
end

app/helpers/costumes_helper.rb
module CostumesHelper
end

app/views/costumes/_costumes_gallery.slim
- if @costumes.present?
  .photos-container
    - costumes.each do |costume|

      .photo-container
        = link_to costume, class: 'link-white ' do
          - if costume.photos.attached?
            = image_tag costume.photos.order(created_at: :asc).first.variant(resize: "300x200^", gravity: :center, crop: "300x200+0+0", interlace: "plane"), class: 'responsive-image'
          - else
            .stub.content-center
              = fa_icon 'image 4x', class: 'text-color-gray'
        .image-costume-photo-info.f-sb
          span = time_ago_in_words(costume.created_at)
          span = fa_icon 'eye', text: costume.impressions_count, left: true, class: "fa-1x"

  .content-center.mt-2 = paginate costumes, window: 1
- else
  .blank-list
    p = t('common.no_costumes_found')
    = link_to (user_signed_in? ? new_costume_path : new_user_session_path), class: 'link-main' do
      .upload = fa_icon 'cloud', text: t('common.upload_costume'), right: true, class: "fa-2x"

app/views/costumes/edit.html.slim
.wrapper
  #costume-form

app/views/costumes/index.html.slim
- unless user_signed_in?
  .welcome
    h1
      = t('common.main_title')
      strong = t('common.main_subtitle')

    = link_to t('common.continue'), new_user_session_path, class: 'btn btn-main mt-1'

.info
  = link_to t('costumes.costumes'), root_path, class: 'link-black'

  = link_to t('events.name'), events_path, class: 'link-gray ml-0-5'

.wrapper
  = render 'layouts/search'
  = render partial: 'costumes/costumes_gallery', locals: { costumes: @costumes }

app/views/costumes/new.html.slim
.wrapper
  - if current_user.confirmed? || current_user.costumes_count < 3
    #costume-form
  - else
    = render partial: 'layouts/need_confirmation'

app/views/costumes/show.slim
.wrapper
  .costume-card
    h1.text-center = title @costume.name
    - if @costume.desc.present?
      .text-center-wb = simple_format @costume.desc
    .content-center
      = link_to @costume.user.name, cosplayer_path(@costume.user), class: 'link-main'
      = flag_icon(@costume.user.country.downcase, title: Country[@costume.user.country].name, class: 'ml-1')
    p.text-center.datetime = time_ago_in_words(@costume.created_at)
    - if user_signed_in? && @costume.user == current_user
      .text-center = link_to t('common.edit'), edit_costume_path(@costume), class: 'link-main'
      .text-center.mt-1 = link_to t('costumes.remove'),
              costume_path(@costume),
              method: :delete,
              class: 'link-alert',
              data: {confirm: t('common.are_you_sure')}

  #costume-images
    // static preloader for time when turbolinks going to show component
    .images-container.mt-2
      - @js_variables[:photos].each do |photo|
        .image-container
         = image_tag photo[:lq_src]

  .costume-comments
    h2 #{t('costumes.comments')} (#{@costume.comments_count})

    - @comments.each do |comment|
      .comment-header
        - if comment.user.photo.attached?
          = image_tag comment.user.photo.variant(resize: "30x30^", gravity: :center, crop: "30x30+0+0", interlace: "plane"),
                  class: 'circle mr-0-5'
        - else
          = image_tag 'avatar.jpg', height: "30", width: "30", class: 'circle mr-0-5'
        = link_to comment.user.name, root_path, class: 'link-main'
        p = time_ago_in_words(comment.created_at)
      .comment-text
        = simple_format(comment.text)

    - if @comments.present?
      .content-center.mt-1.mb-2 = paginate @comments, window: 1

    - if user_signed_in?
      - if current_user.confirmed?
        = form_for [@costume, Comment.new] do |f|
          = f.text_area :text, minlength: 3, maxlength: 455, class: 'text-area'
          .text-right
            = f.submit class: 'mt-1 btn btn-active'
      - else
        = render partial: 'layouts/need_confirmation'

    - else
      = link_to t('costumes.register_to_write_comments'), new_user_session_path, class: 'link-main'