config/routes.rb
Rails.application.routes.draw do
  post 'users/social_auth'
  get 'users/social_auth_vk'
  get '/privacy_policy', to: redirect('/privacy_policy.html')
  resources :push_notification_subscriptions
  resources :events
  resources :costumes do
    resources :comments
    resources :photos, only: [:destroy]
  end
  resources :cosplayers, only: [:show, :edit, :update] do
    member do
      post 'subscribe'
      post 'unsubscribe'
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "costumes#index"
end

app/controllers/cosplayers_controller.rb
class CosplayersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :subscribe, :unsubscribe]

  def show
    @costumes = @user.costumes.order(created_at: :desc).page(params[:page])
    @subscriber = Subscriber.find_by(subscription: current_user, follower: @user)
    @photo_url =
      if @user.photo.attached?
        @user.photo.variant(resize: "250x250^", gravity: :center, crop: "250x250+0+0", interlace: "plane")
      else
        ActionController::Base.helpers.asset_path('avatar.jpg')
      end
    set_meta_tags description: @user.desc,
                  og: {
                      title: "Cosplayer - #{@user.name}",
                      type: 'website',
                      description: @user.desc,
                      image: @photo_url
                  }
    gon.push({endpoint: "/cosplayers/#{@user.id}"})
  end

  def edit
    redirect_to cosplayer_path(current_user) unless can_edit?
  end

  def update

    return redirect_to cosplayer_path(current_user) unless can_edit?
    if current_user.update(user_params)
      if params[:from_react]
        render json: {}, status: 200
      else
        redirect_to cosplayer_path(current_user)
      end
    else
      render 'edit'
    end
  end

  def subscribe
    subscriber = Subscriber.new(subscription: current_user, follower: @user)
    if subscriber.save
      flash[:notice] = t('cosplayers.subscribed_successfully')
    else
      flash[:alert] = t('common.something_went_wrong')
    end
    redirect_to cosplayer_path(@user)
  end

  def unsubscribe
    subscriber = Subscriber.find_by(subscription: current_user, follower: @user)
    if subscriber.destroy
      flash[:notice] = t('cosplayers.unsubscribed_successfully')
    else
      flash[:alert] = t('common.something_went_wrong')
    end
    redirect_to cosplayer_path(@user)
  end

  private

  def find_user
    @user = User.with_eager_loaded_photo.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :desc, :country, :gender, :photo, :website)
  end

  def can_edit?
    current_user == @user
  end
end

app/helpers/cosplayer_helper.rb
module CosplayerHelper
end

app/views/cosplayers/edit.slim
.wrapper
  h1.text-center = t('cosplayers.edit_cosplayers_info')

  - if current_user.errors.any?
    div
      p.alert = t('not_saved', count: current_user.errors.count, resource: User.model_name.human)

      ul
        - current_user.errors.full_messages.each do |msg|
          li= msg

  = form_for current_user, :url => { controller: :cosplayers, action: :update }, :html => {method: :patch} do |f|
    .field
      = f.label :name, class: 'label'
      = f.text_field :name,
              autofocus: true,
              minlength: 3,
              maxlength: 100,
              class: 'text-field'

    .field
      = f.label :country, class: 'label'
      = f.country_select :country,
              autofocus: true,
              minlength: 3,
              maxlength: 100,
              class: 'text-field'

    .field
      = f.label :gender, class: 'label'
      = f.select :gender,
              User.genders.map {|gender| [User.human_attribute_name(gender[0]), gender[0]]},
              minlength: 3,
              maxlength: 100,
              class: 'text-field'

    .field
      = f.label :website, class: 'label'
      = f.text_field :website,
              minlength: 5,
              maxlength: 100,
              class: 'text-field'

    .field
      = f.label :desc, class: 'label'
      = f.text_area :desc,
              minlength: 3,
              maxlength: 455,
              class: 'text-area'

    = f.submit t('common.save'), class: 'mt-1 btn btn-active'

app/views/cosplayers/show.slim
.info
  p
    = t('cosplayers.costumes_number')
    span.ml-0-5 = @user.costumes_count

  p
    = t('cosplayers.gender')
    span.ml-0-5 = User.human_attribute_name(@user.gender)

  p
    = t('cosplayers.followers_count')
    span.ml-0-5 = @user.followers_count

.wrapper-container

  .profile-card

    .content-center.mt-1#static-avatar
      = image_tag @photo_url, class: 'circle'

    - if @user == current_user
      #avatar-editor

    h1.text-center
      = title @user.name
      = flag_icon(@user.country.downcase, title: Country[@user.country].name, class: 'ml-1')

    - if @user.desc.present?
      .text-center-wb = simple_format @user.desc

    - if @user.website.present?
      .mb-1.text-center = link_to @user.website, "http://#{@user.website}", class: 'link-main', target: "_blank"

    - if user_signed_in? && @user != current_user
      .text-center
        - if @subscriber.present?
          = button_to t('cosplayers.unsubscribe'), unsubscribe_cosplayer_path(@user), class: 'btn btn-main mb-1'
        - else
          = button_to t('cosplayers.subscribe'), subscribe_cosplayer_path(@user), class: 'btn btn-inactive mb-1'

    - if user_signed_in? && @user == current_user
      .text-center = link_to t('common.edit'), edit_cosplayer_path(@user), class: 'link-main'
      br
      .text-center = link_to t('layouts.sign_out'),
              destroy_user_session_path,
              method: :delete,
              class: 'link-alert',
              data: { confirm: t('common.are_you_sure') }

= render partial: 'costumes/costumes_gallery', locals: { costumes: @costumes }