config/routes.rb
Rails.application.routes.draw do
  post 'users/social_auth'
  get 'users/social_auth_vk'
  get '/privacy_policy', to: redirect('/privacy_policy.html')
  resources :push_notification_subscriptions
  resources :events
  resources :costumes do
    resources :comments
    resources :photos, only: [:destroy]
  end
  resources :cosplayers, only: [:show, :edit, :update] do
    member do
      post 'subscribe'
      post 'unsubscribe'
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "costumes#index"
end

app/models/event.rb
class Event < ApplicationRecord
  paginates_per 25
  scope :with_eager_loaded_image, -> { eager_load(image_attachment: :blob) }
  has_one_attached :image
  belongs_to :user
  validates_date :date, :on_or_after => lambda { Date.current }
  validates_presence_of :title,
                        :country_code,
                        :place_id,
                        :formatted_address,
                        :lat,
                        :lng,
                        :date,
                        :link

  before_save :clear_link

  def clear_link
    self.link = link.try do |field|
      field
          .sub('https://', '')
          .sub('http://', '')
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events =
      Event
        .with_eager_loaded_image
        .where("date >= ?", DateTime.now)
        .try {|el| params[:country] ? el.where(country_code: params[:country]) : el}
        .order(date: :asc)
        .page(params[:page])
    gon.push({
      countries: countries,
      country_input: params[:country]
    })
  end

  # GET /events/1
  # GET /events/1.json
  def show
    desc = @event.desc.truncate(160)

    set_meta_tags description: desc,
      og: {
        title: "Cosplay event - #{@event.title}",
        type: 'website',
        description: desc,
        image: @event.image.attached? ? @event.image.variant(resize: "1024", interlace: "plane").processed.service_url : nil
      }
  end

  # GET /events/new
  def new
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    gon_data
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event }
        format.json { render :show, status: :created, location: @event }
      else
        format.html {
          gon_data
          render :new
        }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    return redirect_to root_path unless user_event?
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html do
          gon_data
          render :edit
        end
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    return redirect_to root_path unless user_event?
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: t('events.was_destroyed') }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(
      :title,
      :country_code,
      :place_id,
      :formatted_address,
      :lat,
      :lng,
      :date,
      :link,
      :desc,
      :image,
      'date(1i)',
      'date(2i)',
      'date(3i)',
    )
  end

  def user_event?
    current_user == @event.user
  end

  def gon_data
    gon.push({
      country_code: @event.country_code,
      place_id: @event.place_id,
      formatted_address: @event.formatted_address,
      lat: @event.lat,
      lng: @event.lng,
      formatted_address_invalid: @event.errors[:formatted_address].present?
    })
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def countries
    @countries ||= CS.countries.map {|country| { name: country[1], code: country[0] } }
  end
end

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation.mb-1
      p.alert = t('common.should_fill_all_fields')
  div
    = f.label :title
    br
    = f.text_field :title, minlength: 3, maxlength: 100, class: 'text-field'
  #event-form
  .mt-1
    = f.label :date
    = date_select :event, :date
  .mt-1
    = f.label :link
    br
    = f.text_field :link, minlength: 3, maxlength: 100, class: 'text-field'
  .mt-1
    = f.label :desc
    br
    = f.text_area :desc, minlength: 3, maxlength: 1455, class: 'text-area'
  .mt-1
    .mb-1
      = f.label :image
    = f.file_field :image, multiple: false, direct_upload: true, accept: 'image/jpeg'

  = f.submit class: 'actions mt-1 btn btn-active'

app/views/events/_info.slim
.info
  - if user_signed_in? && current_user.subscriptions_count > 0
    = link_to t('cosplayers.costumes.costumes'), costumes_path, class: 'link-gray'
  = link_to t('events.name'), events_path, class: 'link-black ml-0-5'

app/views/events/edit.html.slim
.text-center.mt-1
  h1 = t('events.edit')

.wrapper
  = render 'form'

app/views/events/index.html.slim
= render 'info'
.wrapper
  #events-search
  .events-cards
    - @events.each do |event|
      .event-card
        = link_to event do
          .image
            - if event.image.attached?
              = image_tag event.image.variant(resize: "900x200^", gravity: :center, interlace: "plane"),
                      class: 'mr-0-5'
        .group
          h1 = link_to event.title, event, class: 'link-black'
          .mt-1
            p.posted_by
              '#{t('events.posted_by')}
              = link_to event.user.name, cosplayer_path(event.user), class: 'link-main'
              '
          .mt-1.flex
            = fa_icon 'calendar', class: "fa-1x mr-0-5"
            p = event.date.strftime('%e %B %Y')
          .mt-0-5.flex
            = fa_icon 'globe', class: "fa-1x mr-0-5"
            p = "#{event.formatted_address}"
          .mt-0-5
            = fa_icon 'link', class: "fa-1x mr-0-5"
            = link_to event.link, "http://#{event.link}", class: 'link-main', target: "_blank"
    br
  - if @events.blank?
    .blank-list
      p = t('common.no_events_found')
      = link_to (user_signed_in? ? new_event_path : new_user_session_path), class: 'link-main' do
        .upload = fa_icon 'calendar', text: t('events.create'), right: true, class: "fa-2x"

  .content-center.mt-2 = paginate @events, window: 1

app/views/events/new.html.slim
.text-center.mt-1
  h1 = t('events.new')

.wrapper
  == render 'form'

app/views/events/show.html.slim
= render 'info'
.wrapper
  .event-page
    .list
      .item
        h1 = link_to @event.title, @event, class: 'link-black'
      .item
        p.posted_by
          '#{t('events.posted_by')}
          = link_to @event.user.name, cosplayer_path(@event.user), class: 'link-main'
          '
      .item.flex
        = fa_icon 'calendar', class: "fa-1x mr-0-5"
        p = @event.date.strftime('%e %B %Y')
      .item.flex
        = fa_icon 'globe', class: "fa-1x mr-0-5"
        p = "#{@event.formatted_address}"
      .item
        = fa_icon 'link', class: "fa-1x mr-0-5"
        = link_to @event.link, "http://#{@event.link}", class: 'link-main', target: "_blank"
      - if @event.desc.present?
        .item
          = MarkdownHelper.render(@event.desc).html_safe
    - if user_signed_in? && current_user == @event.user
      = link_to edit_event_path(@event), class: 'mt-1 btn btn-active flex flex-center' do
        = fa_icon 'edit', class: "fa-1x mr-0-5"
        p = t('common.edit')
      = link_to event_path(@event), method: :delete, class: 'mt-1 btn btn-alert flex flex-center' do
        = fa_icon 'trash', class: "fa-1x mr-0-5"
        p = t('common.delete')