config/routes.rb
Rails.application.routes.draw do
  post 'users/social_auth'
  get 'users/social_auth_vk'
  get '/privacy_policy', to: redirect('/privacy_policy.html')
  resources :push_notification_subscriptions
  resources :events
  resources :costumes do
    resources :comments
    resources :photos, only: [:destroy]
  end
  resources :cosplayers, only: [:show, :edit, :update] do
    member do
      post 'subscribe'
      post 'unsubscribe'
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "costumes#index"
end

app/views/layouts/_facebook_sdk.slim
javascript:
  // we need reinitialize SDK because there is an issue related with the blank auth popup
  // @TODO need to rewrite without gloval variables
  FB = null;
  prevFacebookSDKLink = document.getElementById('facebook-jssdk')
  if (prevFacebookSDKLink) {
    prevFacebookSDKLink.remove()
  }

  window.fbAsyncInit = function () {
    FB.init({
      appId: "#{ENV['FACEBOOK_APP_ID']}",
      autoLogAppEvents: true,
      xfbml: true,
      version: 'v3.0',
      status: true,
    });
  };

  (function (d, s, id) {
    let js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {
      return;
    }
    js = d.createElement(s);
    js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/layouts/_flash.slim
- if notice.present?
  p.notice= notice
- if alert.present?
  p.alert= alert

app/views/layouts/_locales.slim
javascript:
  I18n.defaultLocale = "#{I18n.default_locale}"
  I18n.locale = "#{I18n.locale}"
  // I18n.fallbacks = 'en'
  // I18n.available_locales = ['ru', 'en']

app/views/layouts/_nav.slim
.navigation-container
  .navigation
    .logo
      = link_to root_path do
        = image_tag 'logo.png', width: 40, height: 40, class: 'mr-0-5'
        = image_tag 'text_logo.svg', width: 80, height: 35, class: 'mr-0-5'
    .options
      - if user_signed_in?
        = link_to cosplayer_path(current_user) do
          - if current_user.photo.attached?
            = image_tag current_user.photo.variant(resize: "30x30^", gravity: :center, crop: "30x30+0+0", interlace: "plane"),
                  class: 'circle'
          - else
            = image_tag 'avatar.jpg', height: "30", width: "30", class: 'circle'
      - else
        = link_to t('layouts.sign_in'), new_user_session_path

app/views/layouts/_need_confirmation.slim
.text-center.b-c-alert
  p = t('common.confirm_your_email')

app/views/layouts/_privacy.slim
.terms-and-privacy
  p
    '#{t('common.privacy_agreement')}
    = link_to t('common.privacy_policy'), privacy_policy_path, class: 'session-link',  data: { turbolinks: false }
    '

app/views/layouts/_search.slim
= form_for :search, url: root_path, method: :get, html: { class: 'search mb-1' } do |f|
  = f.text_field :name, placeholder: t('common.search'), value: params.dig(:search, :name)

app/views/layouts/application.slim
doctype html
html
  head
    - site_name = 'Casply - cosplay community'
    = display_meta_tags site: site_name, og: { site_name: site_name }
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script src="//vk.com/js/api/openapi.js" type="text/javascript"
    script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=#{ENV['MAPS_JS_API_KEY']}&libraries=places&language=en"
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'slider'
    = stylesheet_pack_tag 'slider'
    = javascript_pack_tag 'avatar_editor'
    = javascript_pack_tag 'social_auth'
    = javascript_pack_tag 'event_form'
    = javascript_pack_tag 'events_search'
    = javascript_pack_tag 'setup_notifications'
    = javascript_pack_tag 'costume_form'
    = javascript_pack_tag 'float_button'
    = stylesheet_pack_tag 'float_button'
    meta content="width=device-width, initial-scale=1" name="viewport" /

  body
    = render 'layouts/locales'
    = Gon::Base.render_data
    = render 'layouts/nav'

    = render 'layouts/flash'
    = yield
    #float-button